title: Home of Stupid Magpie
description: description here.
theme: jekyll-theme-hacker
url: https://github.com/StupidMagpie/StupidMagpie.github.io
author:
  name: StupieMagpie
  email: mzhm803@gmail.com
  url: https://github.com/StupidMagpie/StupidMagpie.github.io
paginate: 10
owner: mzh
year: 2024
